const machine_mod = @import("../decl/machine.zig");
const common = @import("../decl/common.zig");
const instruction_mod = @import("../decl/instruction.zig");
const shim_mod = @import("../decl/shim.zig");

pub const machine = machine_mod.Machine{
    .name = "gba",
    .binary_format = .gba_rom,
    .cpus = &.{
        .{
            .name = "arm7tdmi",
            .isa = .armv4t,
            .clock_hz = 16_777_216,
        },
    },
    .memory_regions = &.{
        .{
            .name = "bios",
            .start = 0x00000000,
            .size = 0x00004000,
            .kind = .rom,
            .permissions = .read_only,
        },
        .{
            .name = "ewram",
            .start = 0x02000000,
            .size = 0x00040000,
            .kind = .ram,
            .permissions = .read_write,
        },
        .{
            .name = "iwram",
            .start = 0x03000000,
            .size = 0x00008000,
            .kind = .ram,
            .permissions = .read_write,
        },
        .{
            .name = "io",
            .start = 0x04000000,
            .size = 0x00000400,
            .kind = .mmio,
            .permissions = .read_write,
        },
        .{
            .name = "rom",
            .start = 0x08000000,
            .size = 0x02000000,
            .kind = .rom,
            .permissions = .read_only,
        },
    },
    .devices = &.{
        .{ .name = "ppu", .kind = .graphics },
        .{ .name = "apu", .kind = .audio },
    },
    .entry = .reset_vector,
    .hle_surfaces = &.{"bios_swi"},
    .save_state = .{ .components = &.{ "cpu", "ewram", "iwram", "io" } },
};

comptime {
    machine_mod.validateComptime(machine);
}

pub const shims: []const shim_mod.ShimDecl = &.{
    .{
        .id = .{
            .kind = .shim,
            .namespace = "gba",
            .name = "Div",
        },
        .state = .verified,
        .args = &.{
            .{ .name = "numerator", .ty = .i32 },
            .{ .name = "denominator", .ty = .i32 },
        },
        .returns = .i32,
        .effects = .pure,
        .tests = &.{
            .{ .name = "positive division", .input = &.{ 10, 2 }, .expected = 5 },
            .{ .name = "negative division", .input = &.{ -9, 3 }, .expected = -3 },
        },
        .doc_refs = &.{
            .{
                .label = "GBATEK BIOS Div",
                .url = "https://problemkaputt.de/gbatek.htm#biosarithmeticfunctions",
            },
        },
        .notes = &.{"Pure arithmetic BIOS helper used as the first shim test surface."},
    },
    .{
        .id = .{
            .kind = .shim,
            .namespace = "gba",
            .name = "Sqrt",
        },
        .state = .implemented,
        .args = &.{
            .{ .name = "value", .ty = .i32 },
        },
        .returns = .i32,
        .effects = .pure,
        .tests = &.{
            .{ .name = "sqrt zero", .input = &.{0}, .expected = 0 },
            .{ .name = "sqrt perfect square", .input = &.{81}, .expected = 9 },
            .{ .name = "sqrt truncates down", .input = &.{15}, .expected = 3 },
        },
        .doc_refs = &.{
            .{
                .label = "GBATEK BIOS Sqrt",
                .url = "https://problemkaputt.de/gbatek.htm#biosarithmeticfunctions",
            },
        },
        .notes = &.{"Pure arithmetic BIOS helper for the next jsmolka BIOS test slice."},
    },
};

pub const instructions: []const instruction_mod.InstructionDecl = &.{
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mov_imm",
        },
        .isa = .armv4t,
        .mnemonic = "mov",
        .encoding = .fixed32,
        .state = .verified,
        .tests = &.{
            .{
                .name = "writes immediate into destination register",
                .input = &.{ 0, 42 },
                .expected = &.{42},
            },
        },
        .doc_refs = &.{
            .{
                .label = "ARM ARM MOV immediate",
                .url = "https://developer.arm.com/documentation",
            },
        },
        .notes = &.{"Tiny instruction surface for phase 0 declaration-backed testing."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mov_reg",
        },
        .isa = .armv4t,
        .mnemonic = "mov",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 interworking surface for register-to-register moves, including thumb high-register copies."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "movs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "movs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-setting immediate moves for NZ updates in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mvn_imm",
        },
        .isa = .armv4t,
        .mnemonic = "mvn",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for immediate bitwise inversion."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mvn_reg",
        },
        .isa = .armv4t,
        .mnemonic = "mvn",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical-not surface for register inversion with NZ flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "movs_reg",
        },
        .isa = .armv4t,
        .mnemonic = "movs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-setting register moves for NZ updates in report paths."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "orr_imm",
        },
        .isa = .armv4t,
        .mnemonic = "orr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for materializing split immediates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "orr_reg",
        },
        .isa = .armv4t,
        .mnemonic = "orr",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical surface for register OR with NZ flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "eor_imm",
        },
        .isa = .armv4t,
        .mnemonic = "eor",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate XOR masking in the ARM arithmetic test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "eor_reg",
        },
        .isa = .armv4t,
        .mnemonic = "eor",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical surface for register XOR with NZ flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bic_imm",
        },
        .isa = .armv4t,
        .mnemonic = "bic",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate bit-clear operations in the ARM arithmetic test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bic_reg",
        },
        .isa = .armv4t,
        .mnemonic = "bic",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical surface for register bit-clear with NZ flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "orr_reg_shift",
        },
        .isa = .armv4t,
        .mnemonic = "orr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for rotated-bit assembly in packed halfword writes."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "and_imm",
        },
        .isa = .armv4t,
        .mnemonic = "and",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate bit masking in tile-format helpers."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "and_reg",
        },
        .isa = .armv4t,
        .mnemonic = "and",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical surface for register AND with NZ flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "add_imm",
        },
        .isa = .armv4t,
        .mnemonic = "add",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for simple pointer construction."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "adds_imm",
        },
        .isa = .armv4t,
        .mnemonic = "adds",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for carry-producing immediate addition."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "adcs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "adcs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for add-with-carry immediate arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "adcs_reg_shift",
        },
        .isa = .armv4t,
        .mnemonic = "adcs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for add-with-carry shifted-register arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "adc_imm",
        },
        .isa = .armv4t,
        .mnemonic = "adc",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for add-with-carry immediate arithmetic without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "sbcs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "sbcs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for subtract-with-carry immediate arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "sbcs_reg",
        },
        .isa = .armv4t,
        .mnemonic = "sbcs",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb arithmetic surface for subtract-with-carry register arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "sbc_imm",
        },
        .isa = .armv4t,
        .mnemonic = "sbc",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for subtract-with-carry immediate arithmetic without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "add_reg",
        },
        .isa = .armv4t,
        .mnemonic = "add",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register-register address arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "add_reg_shift",
        },
        .isa = .armv4t,
        .mnemonic = "add",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register-shifted addition, including ARM pc-as-source quirks."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rsb_imm",
        },
        .isa = .armv4t,
        .mnemonic = "rsb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for reverse-subtract immediate arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rsbs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "rsbs",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb arithmetic surface for negate-style reverse-subtract with NZCV updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rsc_imm",
        },
        .isa = .armv4t,
        .mnemonic = "rsc",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for reverse-subtract-with-carry immediate arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "sub_imm",
        },
        .isa = .armv4t,
        .mnemonic = "sub",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for non-flag subtract-immediate arithmetic."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "subs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "subs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for loop counters and Z-flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "subs_reg",
        },
        .isa = .armv4t,
        .mnemonic = "subs",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb arithmetic surface for register subtract with NZCV updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsl_imm",
        },
        .isa = .armv4t,
        .mnemonic = "lsl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate left shifts used in table indexing."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsl_reg",
        },
        .isa = .armv4t,
        .mnemonic = "lsl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register-counted left shifts without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "asr_imm",
        },
        .isa = .armv4t,
        .mnemonic = "asr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 shift surface for immediate arithmetic right shifts without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "asr_reg",
        },
        .isa = .armv4t,
        .mnemonic = "asr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 shift surface for register-counted arithmetic right shifts without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsls_imm",
        },
        .isa = .armv4t,
        .mnemonic = "lsls",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for immediate left shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "asrs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "asrs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for immediate arithmetic right shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsrs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "lsrs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for immediate logical right shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsls_reg",
        },
        .isa = .armv4t,
        .mnemonic = "lsls",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for register-counted left shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsrs_reg",
        },
        .isa = .armv4t,
        .mnemonic = "lsrs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for register-counted logical right shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "asrs_reg",
        },
        .isa = .armv4t,
        .mnemonic = "asrs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for register-counted arithmetic right shifts that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsr_imm",
        },
        .isa = .armv4t,
        .mnemonic = "lsr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate right shifts in packed pixel helpers."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "lsr_reg",
        },
        .isa = .armv4t,
        .mnemonic = "lsr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register-counted logical right shifts without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ror_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ror",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate rotate-right operations without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rors_imm",
        },
        .isa = .armv4t,
        .mnemonic = "rors",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for immediate rotate-right operations that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ror_reg",
        },
        .isa = .armv4t,
        .mnemonic = "ror",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register-counted rotate-right operations without flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rors_reg",
        },
        .isa = .armv4t,
        .mnemonic = "rors",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for register-counted rotate-right operations that update NZC."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "rrxs",
        },
        .isa = .armv4t,
        .mnemonic = "rrxs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-transition surface for rotate-right-with-extend using the carry flag as input."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mla",
        },
        .isa = .armv4t,
        .mnemonic = "mla",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for multiply-accumulate address math in glyph plotting."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mul",
        },
        .isa = .armv4t,
        .mnemonic = "mul",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 arithmetic surface for plain 32-bit register multiply in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "umull",
        },
        .isa = .armv4t,
        .mnemonic = "umull",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 arithmetic surface for unsigned 64-bit register multiply in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "umlal",
        },
        .isa = .armv4t,
        .mnemonic = "umlal",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 arithmetic surface for unsigned 64-bit multiply-accumulate in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "smull",
        },
        .isa = .armv4t,
        .mnemonic = "smull",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 arithmetic surface for signed 64-bit register multiply in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "smlal",
        },
        .isa = .armv4t,
        .mnemonic = "smlal",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 arithmetic surface for signed 64-bit multiply-accumulate in the ARM test ROM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "swp_word",
        },
        .isa = .armv4t,
        .mnemonic = "swp",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for word swap operations in the ARM test ROM's atomic-memory block."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "swp_byte",
        },
        .isa = .armv4t,
        .mnemonic = "swpb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for byte swap operations in the ARM test ROM's atomic-memory block."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_imm",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for word stores with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_pre",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for pre-index word stores with writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_word_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 wait-loop surface for word loads from MMIO and stack-backed RAM."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_word_imm_signed",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for word loads with subtracting immediate offsets, including PC-relative literals."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_byte_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for zero-extending byte loads with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_byte_reg",
        },
        .isa = .armv4t,
        .mnemonic = "ldrb",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb memory surface for zero-extending byte loads with register offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_halfword_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for zero-extending halfword loads with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_halfword_pre_reg",
        },
        .isa = .armv4t,
        .mnemonic = "ldrh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for pre-index halfword loads with register offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_halfword_pre_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for pre-index halfword loads with immediate writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_halfword_post_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for post-index halfword loads with immediate writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_signed_halfword_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrsh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for sign-extending halfword loads with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_signed_halfword_reg",
        },
        .isa = .armv4t,
        .mnemonic = "ldrsh",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb memory surface for sign-extending halfword loads with register offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_signed_byte_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldrsb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for sign-extending byte loads with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_signed_byte_reg",
        },
        .isa = .armv4t,
        .mnemonic = "ldrsb",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb memory surface for sign-extending byte loads with register offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_word_pre_reg_shift",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for pre-index word loads with register-shifted offsets and writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_word_pre_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for pre-index word loads with immediate writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_word_post_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for post-index word loads with immediate writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldr_pc_post_imm",
        },
        .isa = .armv4t,
        .mnemonic = "ldr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 control-flow surface for resolved post-index `ldr pc, [base], #imm` patterns."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_reg",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for word stores indexed by a register."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_halfword_imm",
        },
        .isa = .armv4t,
        .mnemonic = "strh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for halfword stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_halfword_pre",
        },
        .isa = .armv4t,
        .mnemonic = "strh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 memory surface for halfword stores with pre-index writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_halfword_post",
        },
        .isa = .armv4t,
        .mnemonic = "strh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for halfword stores with post-index pointer bumps."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_byte_imm",
        },
        .isa = .armv4t,
        .mnemonic = "strb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for byte stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_byte_post",
        },
        .isa = .armv4t,
        .mnemonic = "strb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Reserved Phase 1 surface for post-index byte stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_post",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Reserved Phase 1 surface for post-index word stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "b",
        },
        .isa = .armv4t,
        .mnemonic = "b",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for direct unconditional branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "cmp_imm",
        },
        .isa = .armv4t,
        .mnemonic = "cmp",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate compare driving conditional execution."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "cmp_reg",
        },
        .isa = .armv4t,
        .mnemonic = "cmp",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register compare in arithmetic-shift validation paths."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "cmn_imm",
        },
        .isa = .armv4t,
        .mnemonic = "cmn",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate addition that only updates flags."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "cmn_reg",
        },
        .isa = .armv4t,
        .mnemonic = "cmn",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for register addition that only updates flags."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "push_regs",
        },
        .isa = .armv4t,
        .mnemonic = "push",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 stack surface for saving register lists to the descending full stack."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "pop_regs",
        },
        .isa = .armv4t,
        .mnemonic = "pop",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 stack surface for restoring register lists from the ascending stack."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldm_regs",
        },
        .isa = .armv4t,
        .mnemonic = "ldm",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 literal-table surface for loading register pairs from memory-backed tables."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldmib_regs",
        },
        .isa = .armv4t,
        .mnemonic = "ldmib",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for increment-before multi-register loads."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldmda_regs",
        },
        .isa = .armv4t,
        .mnemonic = "ldmda",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for decrement-after multi-register loads."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldmdb_regs",
        },
        .isa = .armv4t,
        .mnemonic = "ldmdb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for decrement-before multi-register loads."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ldm_empty",
        },
        .isa = .armv4t,
        .mnemonic = "ldm",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 ARM7TDMI quirk surface for empty-register-list LDM encodings that still branch through memory and apply 0x40 writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "stmia_regs",
        },
        .isa = .armv4t,
        .mnemonic = "stmia",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for increment-after multi-register stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "stmib_regs",
        },
        .isa = .armv4t,
        .mnemonic = "stmib",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for increment-before multi-register stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "stmda_regs",
        },
        .isa = .armv4t,
        .mnemonic = "stmda",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for decrement-after multi-register stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "stmdb_regs",
        },
        .isa = .armv4t,
        .mnemonic = "stmdb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 block-transfer surface for decrement-before multi-register stores outside the stack aliases."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "stm_empty",
        },
        .isa = .armv4t,
        .mnemonic = "stm",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 ARM7TDMI quirk surface for empty-register-list STM encodings that still store pc+12 and apply 0x40 writeback."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "tst_imm",
        },
        .isa = .armv4t,
        .mnemonic = "tst",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 wait-loop surface for immediate bit tests that only update flags."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "tst_reg",
        },
        .isa = .armv4t,
        .mnemonic = "tst",
        .encoding = .fixed16,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 Thumb logical surface for register bit tests that only update flags."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "teq_imm",
        },
        .isa = .armv4t,
        .mnemonic = "teq",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 helper surface for immediate XOR tests that only update NZ."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "beq",
        },
        .isa = .armv4t,
        .mnemonic = "beq",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for Z-flag equality branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bne",
        },
        .isa = .armv4t,
        .mnemonic = "bne",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for Z-flag-driven loop branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bhs",
        },
        .isa = .armv4t,
        .mnemonic = "bhs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for carry-set branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "blo",
        },
        .isa = .armv4t,
        .mnemonic = "blo",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for carry-clear branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bmi",
        },
        .isa = .armv4t,
        .mnemonic = "bmi",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for negative-sign branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bpl",
        },
        .isa = .armv4t,
        .mnemonic = "bpl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for non-negative branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bvs",
        },
        .isa = .armv4t,
        .mnemonic = "bvs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for overflow-set branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bvc",
        },
        .isa = .armv4t,
        .mnemonic = "bvc",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for no-overflow branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bhi",
        },
        .isa = .armv4t,
        .mnemonic = "bhi",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for unsigned-higher branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bls",
        },
        .isa = .armv4t,
        .mnemonic = "bls",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for unsigned-lower-or-same branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bge",
        },
        .isa = .armv4t,
        .mnemonic = "bge",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-greater-or-equal branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "blt",
        },
        .isa = .armv4t,
        .mnemonic = "blt",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-less-than branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bgt",
        },
        .isa = .armv4t,
        .mnemonic = "bgt",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-greater-than branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ble",
        },
        .isa = .armv4t,
        .mnemonic = "ble",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-less-or-equal branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bl",
        },
        .isa = .armv4t,
        .mnemonic = "bl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 call surface for direct branch-and-link targets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bx_reg",
        },
        .isa = .armv4t,
        .mnemonic = "bx",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 interworking surface for statically-known branch-exchange register targets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bx_lr",
        },
        .isa = .armv4t,
        .mnemonic = "bx",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 return surface for direct bx lr leaves."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "nop",
        },
        .isa = .armv4t,
        .mnemonic = "nop",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 padding surface for ARM hint nops in real test ROMs."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mrs_psr",
        },
        .isa = .armv4t,
        .mnemonic = "mrs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 privileged-state read surface for CPSR/SPSR snapshots."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "msr_psr_imm",
        },
        .isa = .armv4t,
        .mnemonic = "msr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 privileged-state write surface for CPSR/SPSR immediate forms."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "msr_psr_reg",
        },
        .isa = .armv4t,
        .mnemonic = "msr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 privileged-state write surface for CPSR/SPSR register forms."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "exception_return",
        },
        .isa = .armv4t,
        .mnemonic = "subs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 exception-return surface for `subs pc, pc, #imm` with CPSR restore."},
    },
};

test "gba machine validates against the shared schema" {
    try machine_mod.validate(machine);
}
