const machine_mod = @import("../decl/machine.zig");
const common = @import("../decl/common.zig");
const instruction_mod = @import("../decl/instruction.zig");
const shim_mod = @import("../decl/shim.zig");

pub const machine = machine_mod.Machine{
    .name = "gba",
    .binary_format = .gba_rom,
    .cpus = &.{
        .{
            .name = "arm7tdmi",
            .isa = .armv4t,
            .clock_hz = 16_777_216,
        },
    },
    .memory_regions = &.{
        .{
            .name = "bios",
            .start = 0x00000000,
            .size = 0x00004000,
            .kind = .rom,
            .permissions = .read_only,
        },
        .{
            .name = "ewram",
            .start = 0x02000000,
            .size = 0x00040000,
            .kind = .ram,
            .permissions = .read_write,
        },
        .{
            .name = "iwram",
            .start = 0x03000000,
            .size = 0x00008000,
            .kind = .ram,
            .permissions = .read_write,
        },
        .{
            .name = "io",
            .start = 0x04000000,
            .size = 0x00000400,
            .kind = .mmio,
            .permissions = .read_write,
        },
        .{
            .name = "rom",
            .start = 0x08000000,
            .size = 0x02000000,
            .kind = .rom,
            .permissions = .read_only,
        },
    },
    .devices = &.{
        .{ .name = "ppu", .kind = .graphics },
        .{ .name = "apu", .kind = .audio },
    },
    .entry = .reset_vector,
    .hle_surfaces = &.{"bios_swi"},
    .save_state = .{ .components = &.{ "cpu", "ewram", "iwram", "io" } },
};

comptime {
    machine_mod.validateComptime(machine);
}

pub const shims: []const shim_mod.ShimDecl = &.{
    .{
        .id = .{
            .kind = .shim,
            .namespace = "gba",
            .name = "Div",
        },
        .state = .verified,
        .args = &.{
            .{ .name = "numerator", .ty = .i32 },
            .{ .name = "denominator", .ty = .i32 },
        },
        .returns = .i32,
        .effects = .pure,
        .tests = &.{
            .{ .name = "positive division", .input = &.{ 10, 2 }, .expected = 5 },
            .{ .name = "negative division", .input = &.{ -9, 3 }, .expected = -3 },
        },
        .doc_refs = &.{
            .{
                .label = "GBATEK BIOS Div",
                .url = "https://problemkaputt.de/gbatek.htm#biosarithmeticfunctions",
            },
        },
        .notes = &.{"Pure arithmetic BIOS helper used as the first shim test surface."},
    },
};

pub const instructions: []const instruction_mod.InstructionDecl = &.{
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "mov_imm",
        },
        .isa = .armv4t,
        .mnemonic = "mov",
        .encoding = .fixed32,
        .state = .verified,
        .tests = &.{
            .{
                .name = "writes immediate into destination register",
                .input = &.{ 0, 42 },
                .expected = &.{42},
            },
        },
        .doc_refs = &.{
            .{
                .label = "ARM ARM MOV immediate",
                .url = "https://developer.arm.com/documentation",
            },
        },
        .notes = &.{"Tiny instruction surface for phase 0 declaration-backed testing."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "orr_imm",
        },
        .isa = .armv4t,
        .mnemonic = "orr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for materializing split immediates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "add_imm",
        },
        .isa = .armv4t,
        .mnemonic = "add",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for simple pointer construction."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "subs_imm",
        },
        .isa = .armv4t,
        .mnemonic = "subs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for loop counters and Z-flag updates."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_imm",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for word stores with immediate offsets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_word_reg",
        },
        .isa = .armv4t,
        .mnemonic = "str",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for word stores indexed by a register."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_halfword_imm",
        },
        .isa = .armv4t,
        .mnemonic = "strh",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for halfword stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "str_byte_imm",
        },
        .isa = .armv4t,
        .mnemonic = "strb",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for byte stores."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "b",
        },
        .isa = .armv4t,
        .mnemonic = "b",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for direct unconditional branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "beq",
        },
        .isa = .armv4t,
        .mnemonic = "beq",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for Z-flag equality branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bne",
        },
        .isa = .armv4t,
        .mnemonic = "bne",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for Z-flag-driven loop branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bhs",
        },
        .isa = .armv4t,
        .mnemonic = "bhs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for carry-set branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "blo",
        },
        .isa = .armv4t,
        .mnemonic = "blo",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for carry-clear branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bmi",
        },
        .isa = .armv4t,
        .mnemonic = "bmi",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for negative-sign branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bpl",
        },
        .isa = .armv4t,
        .mnemonic = "bpl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for non-negative branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bvs",
        },
        .isa = .armv4t,
        .mnemonic = "bvs",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for overflow-set branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bvc",
        },
        .isa = .armv4t,
        .mnemonic = "bvc",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for no-overflow branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bhi",
        },
        .isa = .armv4t,
        .mnemonic = "bhi",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for unsigned-higher branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bls",
        },
        .isa = .armv4t,
        .mnemonic = "bls",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for unsigned-lower-or-same branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bge",
        },
        .isa = .armv4t,
        .mnemonic = "bge",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-greater-or-equal branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "blt",
        },
        .isa = .armv4t,
        .mnemonic = "blt",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-less-than branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bgt",
        },
        .isa = .armv4t,
        .mnemonic = "bgt",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-greater-than branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "ble",
        },
        .isa = .armv4t,
        .mnemonic = "ble",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 real-ROM surface for signed-less-or-equal branches."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bl",
        },
        .isa = .armv4t,
        .mnemonic = "bl",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 call surface for direct branch-and-link targets."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "bx_lr",
        },
        .isa = .armv4t,
        .mnemonic = "bx",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 return surface for direct bx lr leaves."},
    },
    .{
        .id = .{
            .kind = .instruction,
            .namespace = "armv4t",
            .name = "msr_cpsr_f_imm",
        },
        .isa = .armv4t,
        .mnemonic = "msr",
        .encoding = .fixed32,
        .state = .implemented,
        .tests = &.{},
        .doc_refs = &.{},
        .notes = &.{"Phase 1 flag-surface for direct CPSR_f immediate writes."},
    },
};

test "gba machine validates against the shared schema" {
    try machine_mod.validate(machine);
}
