const std = @import("std");
const Io = std.Io;
const armv4t_decode = @import("armv4t_decode.zig");

pub const OutputMode = enum {
    register_r0_decimal,
    memory_summary,
};

pub const InstructionNode = struct {
    address: u32,
    instruction: armv4t_decode.DecodedInstruction,
};

pub const Function = struct {
    entry_address: u32,
    instructions: []const InstructionNode,
};

pub const Program = struct {
    entry_address: u32,
    functions: []const Function,
    output_mode: OutputMode,

    pub fn deinit(self: Program, allocator: std.mem.Allocator) void {
        for (self.functions) |function| allocator.free(function.instructions);
        allocator.free(self.functions);
    }
};

const guest_state_regs_field = 0;
const guest_state_flag_n_field = 1;
const guest_state_flag_z_field = 2;
const guest_state_flag_c_field = 3;
const guest_state_flag_v_field = 4;
const guest_state_io_field = 5;
const guest_state_palette_field = 6;
const guest_state_vram_field = 7;

const Region = struct {
    field_index: u8,
    field_name: []const u8,
    llvm_len: u32,
    base: u32,
    size: u32,
};

const io_region = Region{
    .field_index = guest_state_io_field,
    .field_name = "io",
    .llvm_len = 1024,
    .base = 0x0400_0000,
    .size = 0x400,
};
const palette_region = Region{
    .field_index = guest_state_palette_field,
    .field_name = "palette",
    .llvm_len = 1024,
    .base = 0x0500_0000,
    .size = 0x400,
};
const vram_region = Region{
    .field_index = guest_state_vram_field,
    .field_name = "vram",
    .llvm_len = 98_304,
    .base = 0x0600_0000,
    .size = 0x18_000,
};
const memory_regions = [_]Region{ io_region, palette_region, vram_region };

pub fn emitModule(writer: *Io.Writer, program: Program) Io.Writer.Error!void {
    try emitPrelude(writer);
    try emitStoreHelpers(writer);
    for (program.functions) |function| {
        try emitGuestFunction(writer, function);
    }
    try emitMain(writer, program);
}

fn emitPrelude(writer: *Io.Writer) Io.Writer.Error!void {
    try writer.print("; generated by hmncli phase1 slice\n", .{});
    try writer.print("%Registers = type [16 x i32]\n", .{});
    try writer.print("%GuestState = type {{ %Registers, i1, i1, i1, i1, [1024 x i8], [1024 x i8], [98304 x i8] }}\n", .{});
    try writer.print("@.fmt_r0 = private unnamed_addr constant [4 x i8] c\"%d\\0A\\00\", align 1\n", .{});
    try writer.print(
        "@.fmt_mem = private unnamed_addr constant [79 x i8] c\"IO0=%08X IO8=%08X PAL0=%08X PAL2=%08X VRAM4000=%08X MAP0800=%08X MAP0804=%08X\\0A\\00\", align 1\n",
        .{},
    );
    try writer.print("declare i32 @printf(ptr, ...)\n", .{});
    try writer.print("declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)\n\n", .{});
    try writer.print("define i32 @shim_gba_Div(ptr %state) {{\n", .{});
    try writer.print("entry:\n", .{});
    try writer.print(
        "  %regs_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_regs_field},
    );
    try writer.print("  %r0_ptr = getelementptr inbounds [16 x i32], ptr %regs_ptr, i32 0, i32 0\n", .{});
    try writer.print("  %r1_ptr = getelementptr inbounds [16 x i32], ptr %regs_ptr, i32 0, i32 1\n", .{});
    try writer.print("  %numerator = load i32, ptr %r0_ptr, align 4\n", .{});
    try writer.print("  %denominator = load i32, ptr %r1_ptr, align 4\n", .{});
    try writer.print("  %result = sdiv i32 %numerator, %denominator\n", .{});
    try writer.print("  store i32 %result, ptr %r0_ptr, align 4\n", .{});
    try writer.print("  ret i32 %result\n", .{});
    try writer.print("}}\n\n", .{});
}

fn emitStoreHelpers(writer: *Io.Writer) Io.Writer.Error!void {
    try emitStoreHelper(writer, 32);
    try emitStoreHelper(writer, 16);
    try emitStoreHelper(writer, 8);
}

fn emitStoreHelper(writer: *Io.Writer, bits: u16) Io.Writer.Error!void {
    try writer.print("define void @hmn_store{d}(ptr %state, i32 %addr, i32 %value) {{\n", .{bits});
    try writer.print("entry:\n", .{});
    for (memory_regions) |region| {
        try writer.print(
            "  %{s}_ptr_{d} = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
            .{ region.field_name, bits, region.field_index },
        );
    }
    try writer.print("  br label %check_region_{d}_{d}\n", .{ bits, 0 });
    for (memory_regions, 0..) |region, index| {
        try emitRegionDispatch(writer, bits, region, index);
    }
    try writer.print("store_ret_{d}:\n", .{bits});
    try writer.print("  ret void\n", .{});
    try writer.print("}}\n\n", .{});
}

fn emitRegionDispatch(
    writer: *Io.Writer,
    bits: u16,
    region: Region,
    index: usize,
) Io.Writer.Error!void {
    try writer.print("check_region_{d}_{d}:\n", .{ bits, index });
    try writer.print("  %region_ge_{d}_{d} = icmp uge i32 %addr, {d}\n", .{ bits, index, region.base });
    try writer.print("  %region_lt_{d}_{d} = icmp ult i32 %addr, {d}\n", .{ bits, index, region.base + region.size });
    try writer.print("  %region_hit_{d}_{d} = and i1 %region_ge_{d}_{d}, %region_lt_{d}_{d}\n", .{
        bits,
        index,
        bits,
        index,
        bits,
        index,
    });
    if (index + 1 < memory_regions.len) {
        try writer.print("  br i1 %region_hit_{d}_{d}, label %store_region_{d}_{d}, label %check_region_{d}_{d}\n", .{
            bits,
            index,
            bits,
            index,
            bits,
            index + 1,
        });
    } else {
        try writer.print("  br i1 %region_hit_{d}_{d}, label %store_region_{d}_{d}, label %store_ret_{d}\n", .{
            bits,
            index,
            bits,
            index,
            bits,
        });
    }

    try writer.print("store_region_{d}_{d}:\n", .{ bits, index });
    try writer.print("  %offset_{d}_{d} = sub i32 %addr, {d}\n", .{ bits, index, region.base });
    try writer.print(
        "  %ptr_{d}_{d} = getelementptr inbounds [{d} x i8], ptr %{s}_ptr_{d}, i32 0, i32 %offset_{d}_{d}\n",
        .{ bits, index, region.llvm_len, region.field_name, bits, bits, index },
    );
    switch (bits) {
        32 => try writer.print("  store i32 %value, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index }),
        16 => {
            try writer.print("  %value16_{d}_{d} = trunc i32 %value to i16\n", .{ bits, index });
            try writer.print("  store i16 %value16_{d}_{d}, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index, bits, index });
        },
        8 => {
            try writer.print("  %value8_{d}_{d} = trunc i32 %value to i8\n", .{ bits, index });
            try writer.print("  store i8 %value8_{d}_{d}, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index, bits, index });
        },
        else => unreachable,
    }
    try writer.print("  br label %store_ret_{d}\n", .{bits});
}

fn emitGuestFunction(writer: *Io.Writer, function: Function) Io.Writer.Error!void {
    try writer.print("define void @guest_{x:0>8}(ptr %state) {{\n", .{function.entry_address});
    try writer.print("entry:\n", .{});
    try emitBranchTo(writer, function.entry_address);
    for (function.instructions) |node| {
        try emitInstructionBlock(writer, function, node);
    }
    try writer.print("guest_return_{x:0>8}:\n", .{function.entry_address});
    try writer.print("  ret void\n", .{});
    try writer.print("}}\n\n", .{});
}

fn emitMain(writer: *Io.Writer, program: Program) Io.Writer.Error!void {
    try writer.print("define i32 @main() {{\n", .{});
    try writer.print("entry:\n", .{});
    try writer.print("  %state = alloca %GuestState, align 4\n", .{});
    try writer.print(
        "  %state_regs_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_regs_field},
    );
    try writer.print(
        "  %state_flag_n_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_flag_n_field},
    );
    try writer.print(
        "  %state_flag_z_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_flag_z_field},
    );
    try writer.print(
        "  %state_flag_c_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_flag_c_field},
    );
    try writer.print(
        "  %state_flag_v_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_flag_v_field},
    );
    try writer.print(
        "  %state_io_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_io_field},
    );
    try writer.print(
        "  %state_palette_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_palette_field},
    );
    try writer.print(
        "  %state_vram_ptr = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
        .{guest_state_vram_field},
    );
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 4 %state_regs_ptr, i8 0, i64 64, i1 false)\n", .{});
    try writer.print("  store i1 false, ptr %state_flag_n_ptr, align 1\n", .{});
    try writer.print("  store i1 false, ptr %state_flag_z_ptr, align 1\n", .{});
    try writer.print("  store i1 false, ptr %state_flag_c_ptr, align 1\n", .{});
    try writer.print("  store i1 false, ptr %state_flag_v_ptr, align 1\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 1 %state_io_ptr, i8 0, i64 1024, i1 false)\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 1 %state_palette_ptr, i8 0, i64 1024, i1 false)\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 1 %state_vram_ptr, i8 0, i64 98304, i1 false)\n", .{});
    try writer.print("  call void @guest_{x:0>8}(ptr %state)\n", .{program.entry_address});
    try emitFinalOutput(writer, program.output_mode);
    try writer.print("  ret i32 0\n", .{});
    try writer.print("}}\n", .{});
}

fn emitInstructionBlock(writer: *Io.Writer, function: Function, node: InstructionNode) Io.Writer.Error!void {
    try writer.print("pc_{x:0>8}:\n", .{node.address});
    switch (node.instruction) {
        .mov_imm => |mov| {
            try emitRegPtr(writer, "state", node.address, "rd", mov.rd);
            try writer.print("  store i32 {d}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ mov.imm, node.address });
            try emitFallthrough(writer, function, node.address + 4);
        },
        .orr_imm => |orr| {
            try emitRegPtr(writer, "state", node.address, "rn", orr.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %orr_val_{x:0>8} = or i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, orr.imm });
            try emitRegPtr(writer, "state", node.address, "rd", orr.rd);
            try writer.print("  store i32 %orr_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try emitFallthrough(writer, function, node.address + 4);
        },
        .add_imm => |add| {
            try emitRegPtr(writer, "state", node.address, "rn", add.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %add_val_{x:0>8} = add i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, add.imm });
            try emitRegPtr(writer, "state", node.address, "rd", add.rd);
            try writer.print("  store i32 %add_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try emitFallthrough(writer, function, node.address + 4);
        },
        .subs_imm => |sub| {
            try emitRegPtr(writer, "state", node.address, "rn", sub.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %sub_val_{x:0>8} = sub i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, sub.imm });
            try emitRegPtr(writer, "state", node.address, "rd", sub.rd);
            try writer.print("  store i32 %sub_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %z_val_{x:0>8} = icmp eq i32 %sub_val_{x:0>8}, 0\n", .{ node.address, node.address });
            try emitFlagZPtr(writer, "state", node.address);
            try writer.print("  store i1 %z_val_{x:0>8}, ptr %flag_z_ptr_{x:0>8}, align 1\n", .{ node.address, node.address });
            try emitFallthrough(writer, function, node.address + 4);
        },
        .store => |store| {
            try emitRegPtr(writer, "state", node.address, "base", store.base);
            try writer.print("  %base_val_{x:0>8} = load i32, ptr %base_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            switch (store.offset) {
                .imm => |imm| {
                    try writer.print("  %addr_{x:0>8} = add i32 %base_val_{x:0>8}, {d}\n", .{ node.address, node.address, imm });
                },
                .reg => |reg_index| {
                    try emitRegPtr(writer, "state", node.address, "offset", reg_index);
                    try writer.print("  %offset_val_{x:0>8} = load i32, ptr %offset_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
                    try writer.print("  %addr_{x:0>8} = add i32 %base_val_{x:0>8}, %offset_val_{x:0>8}\n", .{ node.address, node.address, node.address });
                },
            }
            try emitRegPtr(writer, "state", node.address, "src", store.src);
            try writer.print("  %src_val_{x:0>8} = load i32, ptr %src_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            const helper_bits: u16 = switch (store.size) {
                .byte => 8,
                .halfword => 16,
                .word => 32,
            };
            try writer.print(
                "  call void @hmn_store{d}(ptr %state, i32 %addr_{x:0>8}, i32 %src_val_{x:0>8})\n",
                .{ helper_bits, node.address, node.address },
            );
            try emitFallthrough(writer, function, node.address + 4);
        },
        .branch => |branch| {
            if (branch.cond == .al) {
                if (branch.target == node.address)
                    try emitFunctionReturn(writer, function.entry_address)
                else if (hasAddress(function, branch.target))
                    try emitBranchTo(writer, branch.target)
                else
                    try emitFunctionReturn(writer, function.entry_address);
                return;
            }

            try emitBranchCondition(writer, "state", node.address, branch.cond);
            const has_fallthrough = hasAddress(function, node.address + 4);
            const has_target = hasAddress(function, branch.target);
            if (has_fallthrough and has_target) {
                try writer.print(
                    "  br i1 %branch_cond_{x:0>8}, label %pc_{x:0>8}, label %pc_{x:0>8}\n",
                    .{ node.address, branch.target, node.address + 4 },
                );
            } else if (has_fallthrough) {
                try writer.print(
                    "  br i1 %branch_cond_{x:0>8}, label %guest_return_{x:0>8}, label %pc_{x:0>8}\n",
                    .{ node.address, function.entry_address, node.address + 4 },
                );
            } else if (has_target) {
                try writer.print(
                    "  br i1 %branch_cond_{x:0>8}, label %pc_{x:0>8}, label %guest_return_{x:0>8}\n",
                    .{ node.address, branch.target, function.entry_address },
                );
            } else {
                try emitFunctionReturn(writer, function.entry_address);
            }
        },
        .bl => |bl| {
            try emitRegPtr(writer, "state", node.address, "lr", 14);
            try writer.print("  store i32 {d}, ptr %lr_ptr_{x:0>8}, align 4\n", .{ node.address + 4, node.address });
            try writer.print("  call void @guest_{x:0>8}(ptr %state)\n", .{bl.target});
            try emitFallthrough(writer, function, node.address + 4);
        },
        .bx_lr => {
            try emitFunctionReturn(writer, function.entry_address);
        },
        .msr_cpsr_f_imm => |flags| {
            try emitFlagPtr(writer, "state", node.address, .n);
            try writer.print("  store i1 {s}, ptr %flag_n_ptr_{x:0>8}, align 1\n", .{ boolLiteral(flags.n), node.address });
            try emitFlagPtr(writer, "state", node.address, .z);
            try writer.print("  store i1 {s}, ptr %flag_z_ptr_{x:0>8}, align 1\n", .{ boolLiteral(flags.z), node.address });
            try emitFlagPtr(writer, "state", node.address, .c);
            try writer.print("  store i1 {s}, ptr %flag_c_ptr_{x:0>8}, align 1\n", .{ boolLiteral(flags.c), node.address });
            try emitFlagPtr(writer, "state", node.address, .v);
            try writer.print("  store i1 {s}, ptr %flag_v_ptr_{x:0>8}, align 1\n", .{ boolLiteral(flags.v), node.address });
            try emitFallthrough(writer, function, node.address + 4);
        },
        .swi => |swi| {
            _ = swi;
            try writer.print("  call i32 @shim_gba_Div(ptr %state)\n", .{});
            try emitFallthrough(writer, function, node.address + 4);
        },
    }
}

fn emitFinalOutput(writer: *Io.Writer, output_mode: OutputMode) Io.Writer.Error!void {
    switch (output_mode) {
        .register_r0_decimal => {
            try writer.print(
                "  %state_regs_done = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
                .{guest_state_regs_field},
            );
            try writer.print("  %r0_ptr_done = getelementptr inbounds [16 x i32], ptr %state_regs_done, i32 0, i32 0\n", .{});
            try writer.print("  %result = load i32, ptr %r0_ptr_done, align 4\n", .{});
            try writer.print("  call i32 (ptr, ...) @printf(ptr @.fmt_r0, i32 %result)\n", .{});
        },
        .memory_summary => {
            try writer.print(
                "  %state_io_done = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
                .{guest_state_io_field},
            );
            try writer.print(
                "  %state_palette_done = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
                .{guest_state_palette_field},
            );
            try writer.print(
                "  %state_vram_done = getelementptr inbounds %GuestState, ptr %state, i32 0, i32 {d}\n",
                .{guest_state_vram_field},
            );
            try writer.print("  %io0_ptr = getelementptr inbounds [1024 x i8], ptr %state_io_done, i32 0, i32 0\n", .{});
            try writer.print("  %io0 = load i32, ptr %io0_ptr, align 1\n", .{});
            try writer.print("  %io8_ptr = getelementptr inbounds [1024 x i8], ptr %state_io_done, i32 0, i32 8\n", .{});
            try writer.print("  %io8 = load i32, ptr %io8_ptr, align 1\n", .{});
            try writer.print("  %pal0_ptr = getelementptr inbounds [1024 x i8], ptr %state_palette_done, i32 0, i32 0\n", .{});
            try writer.print("  %pal0_raw = load i16, ptr %pal0_ptr, align 1\n", .{});
            try writer.print("  %pal0 = zext i16 %pal0_raw to i32\n", .{});
            try writer.print("  %pal2_ptr = getelementptr inbounds [1024 x i8], ptr %state_palette_done, i32 0, i32 2\n", .{});
            try writer.print("  %pal2_raw = load i16, ptr %pal2_ptr, align 1\n", .{});
            try writer.print("  %pal2 = zext i16 %pal2_raw to i32\n", .{});
            try writer.print("  %vram4000_ptr = getelementptr inbounds [98304 x i8], ptr %state_vram_done, i32 0, i32 16384\n", .{});
            try writer.print("  %vram4000 = load i32, ptr %vram4000_ptr, align 1\n", .{});
            try writer.print("  %map0800_ptr = getelementptr inbounds [98304 x i8], ptr %state_vram_done, i32 0, i32 2048\n", .{});
            try writer.print("  %map0800_raw = load i16, ptr %map0800_ptr, align 1\n", .{});
            try writer.print("  %map0800 = zext i16 %map0800_raw to i32\n", .{});
            try writer.print("  %map0804_ptr = getelementptr inbounds [98304 x i8], ptr %state_vram_done, i32 0, i32 2052\n", .{});
            try writer.print("  %map0804_raw = load i16, ptr %map0804_ptr, align 1\n", .{});
            try writer.print("  %map0804 = zext i16 %map0804_raw to i32\n", .{});
            try writer.print(
                "  call i32 (ptr, ...) @printf(ptr @.fmt_mem, i32 %io0, i32 %io8, i32 %pal0, i32 %pal2, i32 %vram4000, i32 %map0800, i32 %map0804)\n",
                .{},
            );
        },
    }
}

fn emitRegPtr(
    writer: *Io.Writer,
    state_name: []const u8,
    address: u32,
    prefix: []const u8,
    reg_index: u4,
) Io.Writer.Error!void {
    try writer.print(
        "  %regs_ptr_{s}_{x:0>8} = getelementptr inbounds %GuestState, ptr %{s}, i32 0, i32 {d}\n",
        .{ prefix, address, state_name, guest_state_regs_field },
    );
    try writer.print(
        "  %{s}_ptr_{x:0>8} = getelementptr inbounds [16 x i32], ptr %regs_ptr_{s}_{x:0>8}, i32 0, i32 {d}\n",
        .{ prefix, address, prefix, address, reg_index },
    );
}

const Flag = enum {
    n,
    z,
    c,
    v,
};

fn emitFlagZPtr(
    writer: *Io.Writer,
    state_name: []const u8,
    address: u32,
) Io.Writer.Error!void {
    try emitFlagPtr(writer, state_name, address, .z);
}

fn emitFlagPtr(
    writer: *Io.Writer,
    state_name: []const u8,
    address: u32,
    flag: Flag,
) Io.Writer.Error!void {
    try writer.print(
        "  %{s}_ptr_{x:0>8} = getelementptr inbounds %GuestState, ptr %{s}, i32 0, i32 {d}\n",
        .{ flagPtrPrefix(flag), address, state_name, flagFieldIndex(flag) },
    );
}

fn emitFlagLoad(
    writer: *Io.Writer,
    state_name: []const u8,
    address: u32,
    flag: Flag,
) Io.Writer.Error!void {
    try emitFlagPtr(writer, state_name, address, flag);
    try writer.print(
        "  %{s}_val_{x:0>8} = load i1, ptr %{s}_ptr_{x:0>8}, align 1\n",
        .{ flagPtrPrefix(flag), address, flagPtrPrefix(flag), address },
    );
}

fn emitBranchCondition(
    writer: *Io.Writer,
    state_name: []const u8,
    address: u32,
    cond: armv4t_decode.Cond,
) Io.Writer.Error!void {
    switch (cond) {
        .eq => {
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %branch_cond_{x:0>8} = or i1 %flag_z_val_{x:0>8}, false\n", .{ address, address });
        },
        .ne => {
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %branch_cond_{x:0>8} = xor i1 %flag_z_val_{x:0>8}, true\n", .{ address, address });
        },
        .hs => {
            try emitFlagLoad(writer, state_name, address, .c);
            try writer.print("  %branch_cond_{x:0>8} = or i1 %flag_c_val_{x:0>8}, false\n", .{ address, address });
        },
        .lo => {
            try emitFlagLoad(writer, state_name, address, .c);
            try writer.print("  %branch_cond_{x:0>8} = xor i1 %flag_c_val_{x:0>8}, true\n", .{ address, address });
        },
        .mi => {
            try emitFlagLoad(writer, state_name, address, .n);
            try writer.print("  %branch_cond_{x:0>8} = or i1 %flag_n_val_{x:0>8}, false\n", .{ address, address });
        },
        .pl => {
            try emitFlagLoad(writer, state_name, address, .n);
            try writer.print("  %branch_cond_{x:0>8} = xor i1 %flag_n_val_{x:0>8}, true\n", .{ address, address });
        },
        .vs => {
            try emitFlagLoad(writer, state_name, address, .v);
            try writer.print("  %branch_cond_{x:0>8} = or i1 %flag_v_val_{x:0>8}, false\n", .{ address, address });
        },
        .vc => {
            try emitFlagLoad(writer, state_name, address, .v);
            try writer.print("  %branch_cond_{x:0>8} = xor i1 %flag_v_val_{x:0>8}, true\n", .{ address, address });
        },
        .hi => {
            try emitFlagLoad(writer, state_name, address, .c);
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %not_z_{x:0>8} = xor i1 %flag_z_val_{x:0>8}, true\n", .{ address, address });
            try writer.print("  %branch_cond_{x:0>8} = and i1 %flag_c_val_{x:0>8}, %not_z_{x:0>8}\n", .{ address, address, address });
        },
        .ls => {
            try emitFlagLoad(writer, state_name, address, .c);
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %not_c_{x:0>8} = xor i1 %flag_c_val_{x:0>8}, true\n", .{ address, address });
            try writer.print("  %branch_cond_{x:0>8} = or i1 %not_c_{x:0>8}, %flag_z_val_{x:0>8}\n", .{ address, address, address });
        },
        .ge => {
            try emitFlagLoad(writer, state_name, address, .n);
            try emitFlagLoad(writer, state_name, address, .v);
            try writer.print("  %branch_cond_{x:0>8} = icmp eq i1 %flag_n_val_{x:0>8}, %flag_v_val_{x:0>8}\n", .{ address, address, address });
        },
        .lt => {
            try emitFlagLoad(writer, state_name, address, .n);
            try emitFlagLoad(writer, state_name, address, .v);
            try writer.print("  %branch_cond_{x:0>8} = icmp ne i1 %flag_n_val_{x:0>8}, %flag_v_val_{x:0>8}\n", .{ address, address, address });
        },
        .gt => {
            try emitFlagLoad(writer, state_name, address, .n);
            try emitFlagLoad(writer, state_name, address, .v);
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %eq_nv_{x:0>8} = icmp eq i1 %flag_n_val_{x:0>8}, %flag_v_val_{x:0>8}\n", .{ address, address, address });
            try writer.print("  %not_z_{x:0>8} = xor i1 %flag_z_val_{x:0>8}, true\n", .{ address, address });
            try writer.print("  %branch_cond_{x:0>8} = and i1 %eq_nv_{x:0>8}, %not_z_{x:0>8}\n", .{ address, address, address });
        },
        .le => {
            try emitFlagLoad(writer, state_name, address, .n);
            try emitFlagLoad(writer, state_name, address, .v);
            try emitFlagLoad(writer, state_name, address, .z);
            try writer.print("  %lt_nv_{x:0>8} = icmp ne i1 %flag_n_val_{x:0>8}, %flag_v_val_{x:0>8}\n", .{ address, address, address });
            try writer.print("  %branch_cond_{x:0>8} = or i1 %lt_nv_{x:0>8}, %flag_z_val_{x:0>8}\n", .{ address, address, address });
        },
        .al => unreachable,
    }
}

fn boolLiteral(value: bool) []const u8 {
    return if (value) "true" else "false";
}

fn flagFieldIndex(flag: Flag) u8 {
    return switch (flag) {
        .n => guest_state_flag_n_field,
        .z => guest_state_flag_z_field,
        .c => guest_state_flag_c_field,
        .v => guest_state_flag_v_field,
    };
}

fn flagPtrPrefix(flag: Flag) []const u8 {
    return switch (flag) {
        .n => "flag_n",
        .z => "flag_z",
        .c => "flag_c",
        .v => "flag_v",
    };
}

fn emitFallthrough(writer: *Io.Writer, function: Function, address: u32) Io.Writer.Error!void {
    if (hasAddress(function, address)) {
        try emitBranchTo(writer, address);
    } else {
        try emitFunctionReturn(writer, function.entry_address);
    }
}

fn emitBranchTo(writer: *Io.Writer, address: u32) Io.Writer.Error!void {
    try writer.print("  br label %pc_{x:0>8}\n", .{address});
}

fn emitFunctionReturn(writer: *Io.Writer, entry_address: u32) Io.Writer.Error!void {
    try writer.print("  br label %guest_return_{x:0>8}\n", .{entry_address});
}

fn hasAddress(function: Function, address: u32) bool {
    for (function.instructions) |node| {
        if (node.address == address) return true;
    }
    return false;
}

test "llvm emission includes guest state and a lifted guest entry function" {
    var output: Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();

    const program = Program{
        .entry_address = 0x08000000,
        .functions = &.{
            .{
                .entry_address = 0x08000000,
                .instructions = &.{
                    .{ .address = 0x08000000, .instruction = .{ .mov_imm = .{ .rd = 0, .imm = 10 } } },
                    .{ .address = 0x08000004, .instruction = .{ .mov_imm = .{ .rd = 1, .imm = 2 } } },
                    .{ .address = 0x08000008, .instruction = .{ .swi = .{ .imm24 = 0x000006 } } },
                },
            },
        },
        .output_mode = .register_r0_decimal,
    };
    try emitModule(&output.writer, program);

    try std.testing.expectStringStartsWith(output.writer.buffered(), "; generated by hmncli phase1 slice\n");
    try std.testing.expect(std.mem.indexOf(u8, output.writer.buffered(), "%GuestState = type") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.writer.buffered(), "define void @guest_08000000(ptr %state)") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.writer.buffered(), "call void @guest_08000000(ptr %state)") != null);
}
