const std = @import("std");
const Io = std.Io;
const armv4t_decode = @import("armv4t_decode.zig");

pub const OutputMode = enum {
    register_r0_decimal,
    memory_summary,
};

pub const InstructionNode = struct {
    address: u32,
    instruction: armv4t_decode.DecodedInstruction,
};

pub const Program = struct {
    entry_address: u32,
    instructions: []const InstructionNode,
    output_mode: OutputMode,
};

const Region = struct {
    pointer_name: []const u8,
    llvm_len: u32,
    base: u32,
    size: u32,
};

const io_region = Region{
    .pointer_name = "io",
    .llvm_len = 1024,
    .base = 0x0400_0000,
    .size = 0x400,
};
const palette_region = Region{
    .pointer_name = "palette",
    .llvm_len = 1024,
    .base = 0x0500_0000,
    .size = 0x400,
};
const vram_region = Region{
    .pointer_name = "vram",
    .llvm_len = 98_304,
    .base = 0x0600_0000,
    .size = 0x18_000,
};
const memory_regions = [_]Region{ io_region, palette_region, vram_region };

pub fn emitModule(writer: *Io.Writer, program: Program) Io.Writer.Error!void {
    try emitPrelude(writer);
    try emitStoreHelpers(writer);
    try emitMainPrologue(writer, program.entry_address);
    for (program.instructions) |node| {
        try emitInstructionBlock(writer, program, node);
    }
    try emitHalt(writer, program.output_mode);
    try writer.print("}}\n", .{});
}

fn emitPrelude(writer: *Io.Writer) Io.Writer.Error!void {
    try writer.print("; generated by hmncli phase1 slice\n", .{});
    try writer.print("%Registers = type [16 x i32]\n", .{});
    try writer.print("@.fmt_r0 = private unnamed_addr constant [4 x i8] c\"%d\\0A\\00\", align 1\n", .{});
    try writer.print(
        "@.fmt_mem = private unnamed_addr constant [79 x i8] c\"IO0=%08X IO8=%08X PAL0=%08X PAL2=%08X VRAM4000=%08X MAP0800=%08X MAP0804=%08X\\0A\\00\", align 1\n",
        .{},
    );
    try writer.print("declare i32 @printf(ptr, ...)\n", .{});
    try writer.print("declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg)\n\n", .{});
    try writer.print("define i32 @shim_gba_Div(ptr %regs) {{\n", .{});
    try writer.print("entry:\n", .{});
    try writer.print("  %r0_ptr = getelementptr inbounds [16 x i32], ptr %regs, i32 0, i32 0\n", .{});
    try writer.print("  %r1_ptr = getelementptr inbounds [16 x i32], ptr %regs, i32 0, i32 1\n", .{});
    try writer.print("  %numerator = load i32, ptr %r0_ptr, align 4\n", .{});
    try writer.print("  %denominator = load i32, ptr %r1_ptr, align 4\n", .{});
    try writer.print("  %result = sdiv i32 %numerator, %denominator\n", .{});
    try writer.print("  store i32 %result, ptr %r0_ptr, align 4\n", .{});
    try writer.print("  ret i32 %result\n", .{});
    try writer.print("}}\n\n", .{});
}

fn emitStoreHelpers(writer: *Io.Writer) Io.Writer.Error!void {
    try emitStoreHelper(writer, 32);
    try emitStoreHelper(writer, 16);
    try emitStoreHelper(writer, 8);
}

fn emitStoreHelper(writer: *Io.Writer, bits: u16) Io.Writer.Error!void {
    try writer.print("define void @hmn_store{d}(ptr %io, ptr %palette, ptr %vram, i32 %addr, i32 %value) {{\n", .{bits});
    try writer.print("entry:\n", .{});
    try emitRegionDispatch(writer, bits, 0);
    try writer.print("store_ret_{d}:\n", .{bits});
    try writer.print("  ret void\n", .{});
    try writer.print("}}\n\n", .{});
}

fn emitRegionDispatch(writer: *Io.Writer, bits: u16, index: usize) Io.Writer.Error!void {
    const region = memory_regions[index];
    try writer.print("  %region_ge_{d}_{d} = icmp uge i32 %addr, {d}\n", .{ bits, index, region.base });
    try writer.print("  %region_lt_{d}_{d} = icmp ult i32 %addr, {d}\n", .{ bits, index, region.base + region.size });
    try writer.print("  %region_hit_{d}_{d} = and i1 %region_ge_{d}_{d}, %region_lt_{d}_{d}\n", .{
        bits,
        index,
        bits,
        index,
        bits,
        index,
    });
    if (index + 1 < memory_regions.len) {
        try writer.print("  br i1 %region_hit_{d}_{d}, label %store_region_{d}_{d}, label %check_region_{d}_{d}\n", .{
            bits,
            index,
            bits,
            index,
            bits,
            index + 1,
        });
    } else {
        try writer.print("  br i1 %region_hit_{d}_{d}, label %store_region_{d}_{d}, label %store_ret_{d}\n", .{
            bits,
            index,
            bits,
            index,
            bits,
        });
    }

    try writer.print("store_region_{d}_{d}:\n", .{ bits, index });
    try writer.print("  %offset_{d}_{d} = sub i32 %addr, {d}\n", .{ bits, index, region.base });
    try writer.print(
        "  %ptr_{d}_{d} = getelementptr inbounds [{d} x i8], ptr %{s}, i32 0, i32 %offset_{d}_{d}\n",
        .{ bits, index, region.llvm_len, region.pointer_name, bits, index },
    );
    switch (bits) {
        32 => try writer.print("  store i32 %value, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index }),
        16 => {
            try writer.print("  %value16_{d}_{d} = trunc i32 %value to i16\n", .{ bits, index });
            try writer.print("  store i16 %value16_{d}_{d}, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index, bits, index });
        },
        8 => {
            try writer.print("  %value8_{d}_{d} = trunc i32 %value to i8\n", .{ bits, index });
            try writer.print("  store i8 %value8_{d}_{d}, ptr %ptr_{d}_{d}, align 1\n", .{ bits, index, bits, index });
        },
        else => unreachable,
    }
    try writer.print("  br label %store_ret_{d}\n", .{bits});

    if (index + 1 < memory_regions.len) {
        try writer.print("check_region_{d}_{d}:\n", .{ bits, index + 1 });
        try emitRegionDispatch(writer, bits, index + 1);
    }
}

fn emitMainPrologue(writer: *Io.Writer, entry_address: u32) Io.Writer.Error!void {
    try writer.print("define i32 @main() {{\n", .{});
    try writer.print("entry:\n", .{});
    try writer.print("  %regs = alloca [16 x i32], align 4\n", .{});
    try writer.print("  %io = alloca [1024 x i8], align 4\n", .{});
    try writer.print("  %palette = alloca [1024 x i8], align 4\n", .{});
    try writer.print("  %vram = alloca [98304 x i8], align 4\n", .{});
    try writer.print("  %flag_z = alloca i1, align 1\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 4 %regs, i8 0, i64 64, i1 false)\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 4 %io, i8 0, i64 1024, i1 false)\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 4 %palette, i8 0, i64 1024, i1 false)\n", .{});
    try writer.print("  call void @llvm.memset.p0.i64(ptr align 4 %vram, i8 0, i64 98304, i1 false)\n", .{});
    try writer.print("  store i1 false, ptr %flag_z, align 1\n", .{});
    try emitBranchTo(writer, entry_address);
}

fn emitInstructionBlock(writer: *Io.Writer, program: Program, node: InstructionNode) Io.Writer.Error!void {
    try writer.print("pc_{x:0>8}:\n", .{node.address});
    switch (node.instruction) {
        .mov_imm => |mov| {
            try emitRegPtr(writer, node.address, "rd", mov.rd);
            try writer.print("  store i32 {d}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ mov.imm, node.address });
            try emitFallthrough(writer, program, node.address + 4);
        },
        .orr_imm => |orr| {
            try emitRegPtr(writer, node.address, "rn", orr.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %orr_val_{x:0>8} = or i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, orr.imm });
            try emitRegPtr(writer, node.address, "rd", orr.rd);
            try writer.print("  store i32 %orr_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try emitFallthrough(writer, program, node.address + 4);
        },
        .add_imm => |add| {
            try emitRegPtr(writer, node.address, "rn", add.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %add_val_{x:0>8} = add i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, add.imm });
            try emitRegPtr(writer, node.address, "rd", add.rd);
            try writer.print("  store i32 %add_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try emitFallthrough(writer, program, node.address + 4);
        },
        .subs_imm => |sub| {
            try emitRegPtr(writer, node.address, "rn", sub.rn);
            try writer.print("  %rn_val_{x:0>8} = load i32, ptr %rn_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %sub_val_{x:0>8} = sub i32 %rn_val_{x:0>8}, {d}\n", .{ node.address, node.address, sub.imm });
            try emitRegPtr(writer, node.address, "rd", sub.rd);
            try writer.print("  store i32 %sub_val_{x:0>8}, ptr %rd_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            try writer.print("  %z_val_{x:0>8} = icmp eq i32 %sub_val_{x:0>8}, 0\n", .{ node.address, node.address });
            try writer.print("  store i1 %z_val_{x:0>8}, ptr %flag_z, align 1\n", .{node.address});
            try emitFallthrough(writer, program, node.address + 4);
        },
        .store => |store| {
            try emitRegPtr(writer, node.address, "base", store.base);
            try writer.print("  %base_val_{x:0>8} = load i32, ptr %base_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            switch (store.offset) {
                .imm => |imm| {
                    try writer.print("  %addr_{x:0>8} = add i32 %base_val_{x:0>8}, {d}\n", .{ node.address, node.address, imm });
                },
                .reg => |reg_index| {
                    try emitRegPtr(writer, node.address, "offset", reg_index);
                    try writer.print("  %offset_val_{x:0>8} = load i32, ptr %offset_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
                    try writer.print("  %addr_{x:0>8} = add i32 %base_val_{x:0>8}, %offset_val_{x:0>8}\n", .{ node.address, node.address, node.address });
                },
            }
            try emitRegPtr(writer, node.address, "src", store.src);
            try writer.print("  %src_val_{x:0>8} = load i32, ptr %src_ptr_{x:0>8}, align 4\n", .{ node.address, node.address });
            const helper_bits: u16 = switch (store.size) {
                .byte => 8,
                .halfword => 16,
                .word => 32,
            };
            try writer.print(
                "  call void @hmn_store{d}(ptr %io, ptr %palette, ptr %vram, i32 %addr_{x:0>8}, i32 %src_val_{x:0>8})\n",
                .{ helper_bits, node.address, node.address },
            );
            try emitFallthrough(writer, program, node.address + 4);
        },
        .branch => |branch| switch (branch.cond) {
            .al => if (branch.target == node.address)
                try writer.print("  br label %halt\n", .{})
            else
                try emitBranchTo(writer, branch.target),
            .ne => {
                try writer.print("  %z_branch_{x:0>8} = load i1, ptr %flag_z, align 1\n", .{node.address});
                if (hasAddress(program, node.address + 4)) {
                    if (hasAddress(program, branch.target)) {
                        try writer.print(
                            "  br i1 %z_branch_{x:0>8}, label %pc_{x:0>8}, label %pc_{x:0>8}\n",
                            .{ node.address, node.address + 4, branch.target },
                        );
                    } else {
                        try writer.print(
                            "  br i1 %z_branch_{x:0>8}, label %pc_{x:0>8}, label %halt\n",
                            .{ node.address, node.address + 4 },
                        );
                    }
                } else if (hasAddress(program, branch.target)) {
                    try writer.print(
                        "  br i1 %z_branch_{x:0>8}, label %halt, label %pc_{x:0>8}\n",
                        .{ node.address, branch.target },
                    );
                } else {
                    try writer.print("  br label %halt\n", .{});
                }
            },
        },
        .swi => |swi| {
            _ = swi;
            try writer.print("  call i32 @shim_gba_Div(ptr %regs)\n", .{});
            try emitFallthrough(writer, program, node.address + 4);
        },
    }
}

fn emitHalt(writer: *Io.Writer, output_mode: OutputMode) Io.Writer.Error!void {
    try writer.print("halt:\n", .{});
    switch (output_mode) {
        .register_r0_decimal => {
            try writer.print("  %r0_ptr_done = getelementptr inbounds [16 x i32], ptr %regs, i32 0, i32 0\n", .{});
            try writer.print("  %result = load i32, ptr %r0_ptr_done, align 4\n", .{});
            try writer.print("  call i32 (ptr, ...) @printf(ptr @.fmt_r0, i32 %result)\n", .{});
        },
        .memory_summary => {
            try writer.print("  %io0_ptr = getelementptr inbounds [1024 x i8], ptr %io, i32 0, i32 0\n", .{});
            try writer.print("  %io0 = load i32, ptr %io0_ptr, align 1\n", .{});
            try writer.print("  %io8_ptr = getelementptr inbounds [1024 x i8], ptr %io, i32 0, i32 8\n", .{});
            try writer.print("  %io8 = load i32, ptr %io8_ptr, align 1\n", .{});
            try writer.print("  %pal0_ptr = getelementptr inbounds [1024 x i8], ptr %palette, i32 0, i32 0\n", .{});
            try writer.print("  %pal0_raw = load i16, ptr %pal0_ptr, align 1\n", .{});
            try writer.print("  %pal0 = zext i16 %pal0_raw to i32\n", .{});
            try writer.print("  %pal2_ptr = getelementptr inbounds [1024 x i8], ptr %palette, i32 0, i32 2\n", .{});
            try writer.print("  %pal2_raw = load i16, ptr %pal2_ptr, align 1\n", .{});
            try writer.print("  %pal2 = zext i16 %pal2_raw to i32\n", .{});
            try writer.print("  %vram4000_ptr = getelementptr inbounds [98304 x i8], ptr %vram, i32 0, i32 16384\n", .{});
            try writer.print("  %vram4000 = load i32, ptr %vram4000_ptr, align 1\n", .{});
            try writer.print("  %map0800_ptr = getelementptr inbounds [98304 x i8], ptr %vram, i32 0, i32 2048\n", .{});
            try writer.print("  %map0800_raw = load i16, ptr %map0800_ptr, align 1\n", .{});
            try writer.print("  %map0800 = zext i16 %map0800_raw to i32\n", .{});
            try writer.print("  %map0804_ptr = getelementptr inbounds [98304 x i8], ptr %vram, i32 0, i32 2052\n", .{});
            try writer.print("  %map0804_raw = load i16, ptr %map0804_ptr, align 1\n", .{});
            try writer.print("  %map0804 = zext i16 %map0804_raw to i32\n", .{});
            try writer.print(
                "  call i32 (ptr, ...) @printf(ptr @.fmt_mem, i32 %io0, i32 %io8, i32 %pal0, i32 %pal2, i32 %vram4000, i32 %map0800, i32 %map0804)\n",
                .{},
            );
        },
    }
    try writer.print("  ret i32 0\n", .{});
}

fn emitRegPtr(writer: *Io.Writer, address: u32, prefix: []const u8, reg_index: u4) Io.Writer.Error!void {
    try writer.print(
        "  %{s}_ptr_{x:0>8} = getelementptr inbounds [16 x i32], ptr %regs, i32 0, i32 {d}\n",
        .{ prefix, address, reg_index },
    );
}

fn emitFallthrough(writer: *Io.Writer, program: Program, address: u32) Io.Writer.Error!void {
    if (hasAddress(program, address)) {
        try emitBranchTo(writer, address);
    } else {
        try writer.print("  br label %halt\n", .{});
    }
}

fn emitBranchTo(writer: *Io.Writer, address: u32) Io.Writer.Error!void {
    try writer.print("  br label %pc_{x:0>8}\n", .{address});
}

fn hasAddress(program: Program, address: u32) bool {
    for (program.instructions) |node| {
        if (node.address == address) return true;
    }
    return false;
}

test "llvm emission includes the gba div shim and result print" {
    var output: Io.Writer.Allocating = .init(std.testing.allocator);
    defer output.deinit();

    const program = Program{
        .entry_address = 0x08000000,
        .instructions = &.{
            .{ .address = 0x08000000, .instruction = .{ .mov_imm = .{ .rd = 0, .imm = 10 } } },
            .{ .address = 0x08000004, .instruction = .{ .mov_imm = .{ .rd = 1, .imm = 2 } } },
            .{ .address = 0x08000008, .instruction = .{ .swi = .{ .imm24 = 0x000006 } } },
        },
        .output_mode = .register_r0_decimal,
    };
    try emitModule(&output.writer, program);

    try std.testing.expectStringStartsWith(output.writer.buffered(), "; generated by hmncli phase1 slice\n");
    try std.testing.expect(std.mem.indexOf(u8, output.writer.buffered(), "@shim_gba_Div") != null);
    try std.testing.expect(std.mem.indexOf(u8, output.writer.buffered(), "pc_08000000") != null);
}
